

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ElectricsOnlineWebApp
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ElectricsOnlineEntities : DbContext
{
    public ElectricsOnlineEntities()
        : base("name=ElectricsOnlineEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Order_Products> Order_Products { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ShoppingCartData> ShoppingCartDatas { get; set; }

}

}

