
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ElectricsOnlineWebApp
{

using System;
    using System.Collections.Generic;
    
public partial class Order_Products
{

    public int OrderID { get; set; }

    public int PID { get; set; }

    public int Qty { get; set; }

    public decimal TotalSale { get; set; }



    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

}

}
