
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ElectricsOnlineWebApp
{

using System;
    using System.Collections.Generic;
    
public partial class ShoppingCartData
{

    public int TempOrderID { get; set; }

    public int PID { get; set; }

    public string PName { get; set; }

    public decimal UnitPrice { get; set; }

    public int Quantity { get; set; }

}

}
